return {
  animation = false,
  auto_hide = false,
  tabpages = true,
  clickable = true,
  exclude_ft = {},
  exclude_name = {},
  focus_on_close = "previous",
  hide = { extensions = true, inactive = false },
  highlight_alternate = false,
  highlight_inactive_file_icons = false,
  highlight_visible = true,

  icons = {
    buffer_index = false,
    buffer_number = false,
    button = "",
    diagnostics = {
      [vim.diagnostic.severity.ERROR] = { enabled = true },
      [vim.diagnostic.severity.WARN] = { enabled = false },
      [vim.diagnostic.severity.INFO] = { enabled = false },
      [vim.diagnostic.severity.HINT] = { enabled = true },
    },
    gitsigns = {
      added = { enabled = true, icon = "+" },
      changed = { enabled = true, icon = "~" },
      deleted = { enabled = true, icon = "-" },
    },
    filetype = { custom_colors = false, enabled = true },
    separator = { left = "│", right = "" },
    separator_at_end = true,
    modified = { button = "●" },
    pinned = { button = "", filename = true },
    preset = "default",
  },
  insert_at_end = false,
  insert_at_start = false,
  maximum_padding = 1,
  minimum_padding = 1,
  maximum_length = 30,
  minimum_length = 0,
  semantic_letters = true,
  sidebar_filetypes = { NvimTree = true },
  letters = "asdfjkl;ghnmxcvbziowerutyqpASDFJKLGHNMXCVBZIOWERUTYQP",
  no_name_title = "unnamed buffer",
  sort = { ignore_case = true },
}
