return {
  filters = { dotfiles = false },
  disable_netrw = true,
  hijack_netrw = true,
  hijack_cursor = true,
  hijack_unnamed_buffer_when_opening = false,
  sync_root_with_cwd = true,
  update_focused_file = { enable = true, update_root = false },
  view = {
    side = "left",
    adaptive_size = true,
    width = 35,
    preserve_window_proportions = true,
  },
  git = { enable = true, ignore = true },
  filesystem_watchers = { enable = true },
  actions = {
    open_file = { resize_window = true },
  },
  renderer = {
    root_folder_label = false,
    add_trailing = true,
    group_empty = true,
    highlight_git = true,
    highlight_opened_files = "icon",
    indent_markers = { enable = false },
    icons = {
      show = {
        file = true,
        folder = true,
        folder_arrow = true,
        git = false,
      },

      glyphs = {
        default = "󰈚",
        symlink = "",
        folder = {
          default = "",
          empty = "",
          empty_open = "",
          open = "",
          symlink = "",
          symlink_open = "",
          arrow_open = "",
          arrow_closed = "",
        },
        git = {
          unstaged = "✗",
          staged = "✓",
          unmerged = "",
          renamed = "➜",
          untracked = "★",
          deleted = "",
          ignored = "◌",
        },
      },
    },
  },
}
