return {
  ensure_installed = {
    "lua",
    "vim",
    "vimdoc",
    "typescript",
    "javascript",
    "html",
    "css",
    "bash",
    "scss",
    "toml",
    "jsdoc",
    "tsx",
    "markdown",
    "markdown_inline",
    "sql",
    "prisma",
  },
  sync_install = false,
  auto_install = true,
  highlight = { enable = true, use_languagetree = true },
  indent = { enable = true },
}
